# Generated by Django 4.1.3 on 2022-12-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_sells_item_remove_sells_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sells',
            name='username',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
