# Generated by Django 4.1.3 on 2022-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_sells_item_sells_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sells',
            old_name='username',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='sells',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
